spring:
  application:
    name: shop
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/shop_db
    username: postgres
    password: ${DB_PASSWORD}
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml

logging:
  file:
    name: logs/log.log
  level:
    root: info